#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <filesystem>
#include "TerrainMeshBuilder.h"
#include "AddressableTileStructures.hpp"

namespace fs = std::filesystem;

int main() {
  std::cout << "========================================\n";
  std::cout << "   RUNNING FULL SPATIAL PACKER PIPELINE\n";
  std::cout << "========================================\n\n";

  // Define all the LOD configurations generated by the Python step
  struct LODConfig { int level; int size; };
  std::vector<LODConfig> lods = {
      {0, 2049}, {1, 1025}, {2, 513}, {3, 257}, {4, 129}, {5, 65}, {6, 33}
  };

  std::vector<TileDescriptor> indexTable;
  std::vector<std::vector<QuantizedVertex>> allPackedPayloads;

  // simplify space partition and tree traversals for testing,process each individual level file sequentially for now.
  for (const auto& lod : lods) {
    std::string filename = "../data_bins/lod_" + std::to_string(lod.level) + "_" + std::to_string(lod.size) + "x" + std::to_string(lod.size) + ".bin";
    fs::path targetPath = fs::absolute(filename);

    if (!fs::exists(targetPath)) {
      std::cerr << "Missing data dependency: " << filename << "\n";
      return 1;
    }

    // Read raw float elements
    std::ifstream file(targetPath, std::ios::binary | std::ios::ate);
    std::streamsize fileSize = file.tellg();
    file.seekg(0, std::ios::beg);

    int expectedElements = lod.size * lod.size;
    std::vector<float> rawHeights(expectedElements);
    file.read(reinterpret_cast<char*>(rawHeights.data()), fileSize);


    AABB tileBox;
    std::vector<QuantizedVertex> packedData = TerrainMeshBuilder::BuildQuantizedMesh(rawHeights, lod.size, tileBox);

    // Track the metadata onto the Index Table
    TileDescriptor descriptor{};
    descriptor.lodLevel = lod.level;
    descriptor.tileX = 0; // Root coordinates for demonstration
    descriptor.tileY = 0;
    descriptor.vertexCount = static_cast<uint32_t>(packedData.size());
    descriptor.minX = tileBox.minX; descriptor.minY = tileBox.minY; descriptor.minZ = tileBox.minZ;
    descriptor.maxX = tileBox.maxX; descriptor.maxY = tileBox.maxY; descriptor.maxZ = tileBox.maxZ;

    indexTable.push_back(descriptor);
    allPackedPayloads.push_back(packedData);

    std::cout << "Processed Level " << lod.level << " [" << lod.size << "x" << lod.size
      << "] -> Generated " << packedData.size() << " vertices. Skirt autogenerated\n";
  }

  // Write the unified binary database archive file out to disk
  std::string outArchiveName = "world.terrain";
  std::ofstream outFile(outArchiveName, std::ios::binary);

  ArchiveHeader header;
  header.totalTiles = static_cast<uint32_t>(indexTable.size());

  // Write placeholder header and index table first to compute proper payload offsets
  outFile.write(reinterpret_cast<char*>(&header), sizeof(ArchiveHeader));

  // Calculate byte offsets dynamically
  uint64_t currentPayloadOffset = sizeof(ArchiveHeader) + (indexTable.size() * sizeof(TileDescriptor));
  for (size_t i = 0; i < indexTable.size(); ++i) {
    indexTable[i].byteOffset = currentPayloadOffset;
    currentPayloadOffset += allPackedPayloads[i].size() * sizeof(QuantizedVertex);
  }

  // Write finalized Index Table
  outFile.write(reinterpret_cast<char*>(indexTable.data()), indexTable.size() * sizeof(TileDescriptor));

  // Blast all vertex payloads sequentially into memory back-to-back
  for (const auto& payload : allPackedPayloads) {
    outFile.write(reinterpret_cast<const char*>(payload.data()), payload.size() * sizeof(QuantizedVertex));
  }

  std::cout << "\nSerialization Complete!\n";
  std::cout << " -> Archive File Created: " << fs::absolute(outArchiveName).string() << "\n";
  std::cout << " -> Final File Size:      " << outFile.tellp() << " Bytes.\n";

  return 0;
}